/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as StatsRouteRouteImport } from './routes/stats/route'
import { Route as IssuesRouteRouteImport } from './routes/issues/route'
import { Route as ImportRouteRouteImport } from './routes/import/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportIndexRouteImport } from './routes/import/index'
import { Route as LabelDetailIdRouteImport } from './routes/label-detail/$id'
import { Route as ImportSinglesRouteImport } from './routes/import/singles'
import { Route as ImportAutoRouteImport } from './routes/import/auto'
import { Route as ImportAlbumRouteImport } from './routes/import/album'
import { Route as ArtistDetailSourceIdRouteImport } from './routes/artist-detail/$source/$id'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRouteRoute = StatsRouteRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRouteRoute = IssuesRouteRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRouteRoute = ImportRouteRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportIndexRoute = ImportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImportRouteRoute,
} as any)
const LabelDetailIdRoute = LabelDetailIdRouteImport.update({
  id: '/label-detail/$id',
  path: '/label-detail/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportSinglesRoute = ImportSinglesRouteImport.update({
  id: '/singles',
  path: '/singles',
  getParentRoute: () => ImportRouteRoute,
} as any)
const ImportAutoRoute = ImportAutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => ImportRouteRoute,
} as any)
const ImportAlbumRoute = ImportAlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => ImportRouteRoute,
} as any)
const ArtistDetailSourceIdRoute = ArtistDetailSourceIdRouteImport.update({
  id: '/artist-detail/$source/$id',
  path: '/artist-detail/$source/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRouteRouteWithChildren
  '/issues': typeof IssuesRouteRoute
  '/stats': typeof StatsRouteRoute
  '/$': typeof SplatRoute
  '/import/album': typeof ImportAlbumRoute
  '/import/auto': typeof ImportAutoRoute
  '/import/singles': typeof ImportSinglesRoute
  '/label-detail/$id': typeof LabelDetailIdRoute
  '/import/': typeof ImportIndexRoute
  '/artist-detail/$source/$id': typeof ArtistDetailSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/issues': typeof IssuesRouteRoute
  '/stats': typeof StatsRouteRoute
  '/$': typeof SplatRoute
  '/import/album': typeof ImportAlbumRoute
  '/import/auto': typeof ImportAutoRoute
  '/import/singles': typeof ImportSinglesRoute
  '/label-detail/$id': typeof LabelDetailIdRoute
  '/import': typeof ImportIndexRoute
  '/artist-detail/$source/$id': typeof ArtistDetailSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRouteRouteWithChildren
  '/issues': typeof IssuesRouteRoute
  '/stats': typeof StatsRouteRoute
  '/$': typeof SplatRoute
  '/import/album': typeof ImportAlbumRoute
  '/import/auto': typeof ImportAutoRoute
  '/import/singles': typeof ImportSinglesRoute
  '/label-detail/$id': typeof LabelDetailIdRoute
  '/import/': typeof ImportIndexRoute
  '/artist-detail/$source/$id': typeof ArtistDetailSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/issues'
    | '/stats'
    | '/$'
    | '/import/album'
    | '/import/auto'
    | '/import/singles'
    | '/label-detail/$id'
    | '/import/'
    | '/artist-detail/$source/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/issues'
    | '/stats'
    | '/$'
    | '/import/album'
    | '/import/auto'
    | '/import/singles'
    | '/label-detail/$id'
    | '/import'
    | '/artist-detail/$source/$id'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/issues'
    | '/stats'
    | '/$'
    | '/import/album'
    | '/import/auto'
    | '/import/singles'
    | '/label-detail/$id'
    | '/import/'
    | '/artist-detail/$source/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRouteRoute: typeof ImportRouteRouteWithChildren
  IssuesRouteRoute: typeof IssuesRouteRoute
  StatsRouteRoute: typeof StatsRouteRoute
  SplatRoute: typeof SplatRoute
  LabelDetailIdRoute: typeof LabelDetailIdRoute
  ArtistDetailSourceIdRoute: typeof ArtistDetailSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/': {
      id: '/import/'
      path: '/'
      fullPath: '/import/'
      preLoaderRoute: typeof ImportIndexRouteImport
      parentRoute: typeof ImportRouteRoute
    }
    '/label-detail/$id': {
      id: '/label-detail/$id'
      path: '/label-detail/$id'
      fullPath: '/label-detail/$id'
      preLoaderRoute: typeof LabelDetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/singles': {
      id: '/import/singles'
      path: '/singles'
      fullPath: '/import/singles'
      preLoaderRoute: typeof ImportSinglesRouteImport
      parentRoute: typeof ImportRouteRoute
    }
    '/import/auto': {
      id: '/import/auto'
      path: '/auto'
      fullPath: '/import/auto'
      preLoaderRoute: typeof ImportAutoRouteImport
      parentRoute: typeof ImportRouteRoute
    }
    '/import/album': {
      id: '/import/album'
      path: '/album'
      fullPath: '/import/album'
      preLoaderRoute: typeof ImportAlbumRouteImport
      parentRoute: typeof ImportRouteRoute
    }
    '/artist-detail/$source/$id': {
      id: '/artist-detail/$source/$id'
      path: '/artist-detail/$source/$id'
      fullPath: '/artist-detail/$source/$id'
      preLoaderRoute: typeof ArtistDetailSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ImportRouteRouteChildren {
  ImportAlbumRoute: typeof ImportAlbumRoute
  ImportAutoRoute: typeof ImportAutoRoute
  ImportSinglesRoute: typeof ImportSinglesRoute
  ImportIndexRoute: typeof ImportIndexRoute
}

const ImportRouteRouteChildren: ImportRouteRouteChildren = {
  ImportAlbumRoute: ImportAlbumRoute,
  ImportAutoRoute: ImportAutoRoute,
  ImportSinglesRoute: ImportSinglesRoute,
  ImportIndexRoute: ImportIndexRoute,
}

const ImportRouteRouteWithChildren = ImportRouteRoute._addFileChildren(
  ImportRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRouteRoute: ImportRouteRouteWithChildren,
  IssuesRouteRoute: IssuesRouteRoute,
  StatsRouteRoute: StatsRouteRoute,
  SplatRoute: SplatRoute,
  LabelDetailIdRoute: LabelDetailIdRoute,
  ArtistDetailSourceIdRoute: ArtistDetailSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
